# Generated by Django 5.1 on 2024-09-04 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('telegram', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=20)),
                ('salary', models.IntegerField(null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='all_cvs/')),
                ('status', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='authentication.customuser')),
                ('vacancy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='vacancies.vacancie')),
            ],
        ),
    ]
